#ifndef ROBOMASTER_APP_EVENTS_H
#define ROBOMASTER_APP_EVENTS_H

#define ROBOMASTER_APP_INIT_INF_EID      1
#define ROBOMASTER_APP_NOOP_INF_EID      2
#define ROBOMASTER_APP_CMD_ERR_EID       3
#define ROBOMASTER_APP_PIPE_ERR_EID      4

#endif /* ROBOMASTER_APP_EVENTS_H */
